# See https://wiki.hyprland.org/Configuring/Keywords/ for more variable settings
# These configs are mostly for laptops. This is addemdum to Keybinds.conf

$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserConfigs = $HOME/.config/hypr/UserConfigs

binde = , xf86KbdBrightnessDown, exec, $scriptsDir/BrightnessKbd.sh --dec #Keyboard brightness Down
binde = , xf86KbdBrightnessUp, exec, $scriptsDir/BrightnessKbd.sh --inc #Keyboard brightness up
binde = , xf86MonBrightnessDown, exec, $scriptsDir/Brightness.sh --dec
binde = , xf86MonBrightnessUp, exec, $scriptsDir/Brightness.sh --inc

# Hyprlock
bindl = , switch:on:Lid Switch, exec, hyprlock --grace 0
bindl = , switch:off:Lid Switch, exec, hyprlock --grace 0

