# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule {
  name = Global 98% Opacity
	match:class = .+

	opacity = 0.98
}

windowrule {
  name = Float Proton Pass
	match:class = Proton Pass

	float = true
	center = true
  size	= 1170 730

	opacity = 0.95 0.50
}

windowrule {
  name = Zen Browser Blur
	match:class = zen.*

	opacity = 0.95
}

windowrule {
  name = VsCode
	match:class = code

	opacity = 0.95
}

windowrule {
  name = Deezer
	match:class = deezer.*

	opacity = 0.95
}

